[package]
name = "structured-agent-interpreter-runtime"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }

[dependencies]
structured-agent-runtime = { path = "../structured-agent-runtime" }
structured-agent-il = { path = "../structured-agent-il" }
async-trait = "0.1"
arrow = { version = "57.2.0", default-features = false }
schemars = "0.8"
